# Versi API
apiVersion: v1

# Kind adalah nilai string yang mewakili sumber daya REST yang diwakili oleh objek ini
# Secret menyimpan data rahasia dari jenis tertentu
kind: Secret

metadata:
  # Nama rahasia
  name: mongo-secret
  # Namespace rahasia
  namespace: karsajobs-ns

# Digunakan untuk memfasilitasi penanganan program dari data rahasia
type: Opaque

# Data rahasia yang akan disimpan
data:
  MONGO_ROOT_USERNAME: YWRtaW4= # admin
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # supersecretpassword
